export const ctsFiles = {
    global_explainability: 'global_explainability.csv',
    global_target_distribution:'global_target_distribution.csv',
    global_target_distribution_json:'global_target_distribution.json',
    global_graph_description: 'global_graph_description.csv',
    global_graph_nodes: 'global_graph_nodes.csv',
    global_graph_edges: 'global_graph_edges.csv',
    local_dataset_reliability: 'local_dataset_reliability.csv',
    local_reason_why: 'local_reason_why.csv',
    local_graph_nodes: 'local_graph_nodes.csv',
    local_graph_edges: 'local_graph_edges.csv',
    input_dataset: '[DEPRECATED]_input_dataset.csv',
    input_dataset_discretized: '[DEPRECATED]_input_dataset_discretized.csv',
    global_target_explainability: '[DEPRECATED]_global_target_explainability.csv',
    local_explainability:'[DEPRECATED]_local_explainability.csv',
    fairness_sumarize_criterias: 'fairness_sumarize_criterias.csv',
    fairness_confusion_matrix: 'fairness_confusion_matrix.csv',
    fairness_highest_correlation: 'fairness_highest_correlation.csv',
    fairness_independence: 'fairness_independence.csv',
    fairness_separation: 'fairness_separation.csv',
    fairness_sufficience: 'fairness_sufficience.csv',
};
