export const ctsGlobal = {
    titleApp: 'XAiWeb',
    initial_component: 'global',
    initial_language: 'es',
    feature_limit: 10,
    frecuency_limit: -1,
    downloading_message: 'Generating and downloading image...',
    image_extension: '.png',
    label_global_Features: 'Global Features Importance',
    label_global_distribution: 'Global Target Distribution',
    label_global_target_Features: 'Global Target Features',
    label_global_target_HeatMap: 'Global Target HeatMap',
    label_global_target_Features_values_importance: 'Global Target Features-values importance',
    label_global_target_Features_values_relations: 'Global Target Features-values relations',
    label_local_target_Features_values_importance: 'Local Features-values importance',
    label_local_target_Features_values_relations: 'Local Features-values relations',
    label_fairness_criteria_score: 'Fairness Criterias Score',
    label_fairness_confussion_matrix: 'Fairness Confussion Matrix',
    label_fairness_feature_fairness_criterias: 'Fairness Feature Criterias',
};
