export const jsonFiles = {
    global_explainability: 'global_explainability.json',
    global_target_distribution:'global_target_distribution.json',
    global_target_distribution_json:'global_target_distribution.json',
    global_graph_description: 'global_graph_description.json',
    global_graph_nodes: 'global_graph_nodes.json',
    global_graph_edges: 'global_graph_edges.json',
    local_dataset_reliability: 'local_dataset_reliability.json',
    local_reason_why: 'local_reason_why.json',
    local_graph_nodes: 'local_graph_nodes.json',
    local_graph_edges: 'local_graph_edges.json',
    input_dataset: '[DEPRECATED]_input_dataset.json',
    input_dataset_discretized: '[DEPRECATED]_input_dataset_discretized.json',
    global_target_explainability: '[DEPRECATED]_global_target_explainability.json',
    local_explainability:'[DEPRECATED]_local_explainability.json',
    fairness_sumarize_criterias: 'fairness_sumarize_criterias.json',
    fairness_confusion_matrix: 'fairness_confusion_matrix.json',
    fairness_highest_correlation: 'fairness_highest_correlation.json',
    fairness_independence: 'fairness_independence.json',
    fairness_separation: 'fairness_separation.json',
    fairness_sufficiency: 'fairness_sufficiency.json',
};
